### ISSUE TITLE
Request takeover of hex package name

### ISSUE THREAD

**Issue by bryannaegele** [ryanwinchester/elixir-uuid#18]
Hey @ryanwinchester. After digging through everything in `elixir_uuid` about trying to get updates done and getting no response, I saw that you forked and published this other package. Given the number of libraries that depend on `elixir_uuid`, I recommend attempting to take over the package on hex. It's a fairly straightforward process and I expect Hex would agree with the transfer request as this situation could certainly be construed as an abandoned package at this point.

https://hex.pm/policies/dispute

**Comment by ryanwinchester** [comment]
I'll give it some thought. However, it _feels_ to me like it's a bit hostile to do that.

**Comment by bryannaegele** [comment]
I hear ya but there's been offers by several folks, including yourself, to take over maintainership for ~3 years now and it's going on 2 years since they've even responded to anyone for even the most basic fixes (crypto) on a package that's depended on by >200 packages. The purpose of the dispute process is there to prevent fracturing and duplication of packages due to abandonment. It's not as if it's a hostile takeover due to differences of opinion. At the very least, they'd have to respond within 30 days to the request, so maybe that moves things along to get maintainers added to the existing repo/package.

It's ultimately up to you, but I wanted to point out there is a process available and I think it's worth pursuing for this package. 👍🏻

**Comment by davydog187** [comment]
Hey @ryanwinchester any further thoughts on this? I agree with @bryannaegele, and just ran into this fracturing issue myself.

**Comment by ryanwinchester** [comment]
Hi folks.

I've thought about it for a while and I think it's better to use:

 * https://github.com/bitwalker/uniq
 * https://github.com/bitwalker/uniq_compat (for `elixir_uuid` compatibility)

It has the compatibility library as well as UUID v6 and v7 support ([added by yours truly](https://github.com/bitwalker/uniq/pull/4)).

I'm going to archive this repo to lessen the fragmentation.
