### ISSUE TITLE
Request for UUID V7 Implementation

### ISSUE THREAD

**Issue by derpycoder** [ryanwinchester/elixir-uuid#19]
Hi Seven Shores Team,

I was searching for Unique Id generator and came across several Implementations:

---

- Default UUID package - Unmaintained.

- ULID - Pretty url, sortable, binary. but has milisecond granularity.
- ExKsuid - Pretty url, sortable, binary, but with 1 second granularity.

- NanoId - Random, pretty, custom alphabets, great for slugs sharing but uses string and is not-sortable.

- Finally: Elixir UUID Utils - with UUID V6 - Standard, sortable, with nano second granularity for great index locality!

---

> Implementations SHOULD utilize [UUID7](https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html#uuidv6) over UUID version 1 and 6 if possible. - IETF

---

Now, I am torn between ULID, KSUID & UUID V6 / V7.

Will V7 be implemented? (because I think it would be great as it will be based on a standard supported by many and also nanosecond granularity rocks)

**Comment by ryanwinchester** [comment]
Thanks. I will look into this more.

**Comment by ryanwinchester** [comment]
I am considering archiving this repository soon in favour of recommending https://github.com/bitwalker/uniq

I've also sent a PR there for v7: https://github.com/bitwalker/uniq/pull/4
